[package]
name="hmi_server"
version="0.1.0"
edition = "2024"

[[bin]]
name="hmi_server"

[dependencies]
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread", "time"] }
tokio-stream = "0.1"
warp = { version = "0.3", features = ["tls"] }
openfmb = {git="https://github.com/openenergysolutions/openfmb-rs", rev = "2d0cfb805ed682d0af3b02dd47d22fbf94d3a5d8"}
openfmb-messages-ext = {git="https://github.com/openenergysolutions/openfmb-rs", features = ["nats-async"], rev = "2d0cfb805ed682d0af3b02dd47d22fbf94d3a5d8"}
microgrid-protobuf = {git="https://github.com/openenergysolutions/openfmb-rs", rev = "2d0cfb805ed682d0af3b02dd47d22fbf94d3a5d8"}
serde = {version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
futures = { version = "0.3.5", default-features = false }
uuid = {version = "1.1.2", features = ["serde", "v4"]}
log = "0.4.11"
fern = { version = "0.6", features = ["colored"] }
env_logger = "0.10.0"
static_dir = "0.2.0"
async-nats = "0.39.0"
config = "0.13.3"
jsonwebtoken = "8.1.0"
thiserror = "1.0.21"
chrono = "0.4.26"
bytes = "1"
prost = "0.10.4"
pwhash = "1.0.0"
lazy_static = "1.4.0"
timer = "0.2.0"
roxmltree = "0.18.0"
rand = "0.9.0"
openidconnect = { version = "4.0.0", features = ["reqwest"] }