[package]
name="hmi_server"
version="0.0.1"
edition = "2018"

[[bin]]
name="hmi_server"

[dependencies]
tokio = { version = "0.2", features = ["macros", "sync", "rt-threaded"] }
warp = { version = "0.2.4", features = ["tls"] }
serde = {version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
futures = { version = "0.3.5", default-features = false }
uuid = { version = "0.7", features = ["serde", "v4"] }
log = "0.4.11"
env_logger = "0.7.1"
static_dir = "0.1.3"
inpm = { version="0.2.0", features=["warp"]}
pretty_env_logger = "0.4.0"
circuit_segment_coordinator = {path = "../../../rust/coordination-service/coordination-service"}
riker = {git="https://github.com/bfrog/riker", branch="0.4.1_stable_dashmap"}
nats = "0.7"
config = "0.10.1"
