[coordinator]
environment = "dev"
# environment = "prod"
app_name = "CircuitSegmentCoordinator"
modules = ["publisher", "subscriber", "persistor", "device"]
cursive_ui_enabled = false


[subscriber]
source = "openfmb_file"

[openfmb_file_subscriber]
filename = "../datafiles/capture_10.txt"
# filename = "capture-10072019.txt"

[openfmb_nats_subscriber]
prod_uri = "microgrid.mthollylab.io:32224"
dev_uri = "127.0.0.1:4222"

[battery]
min_soc_soft = "0.26"
min_soc_hard = "0.23"
max_soc_soft = "0.8"
max_soc_hard = "0.9"

[tests]
ess_start_discharge_rate = "19000"
ess_start_charge_rate = "-122000"



[circuit_segment_devices]
# satec_aux_abb
satec_aux_abb_dnp3= {mrid="3feccf53-d4b4-4c52-b1f0-79450cacdc20", name="SATEC AUX ABB"}
abb_pcs100 = {mrid="836a8638-b448-4961-8258-47aa18e05f65", name="Battery Inverter", min_soc=20.0, max_soc=90.0, discharge_to=80.0}
way1 = {mrid="e6768784-48ad-40e9-af2a-9676413d4d6a", name="Way 1"}
way2 = {mrid="894bc1be-507a-4845-8f2c-b20de8b223aa", name="Way 2"}
way3 = {mrid="66228596-99ed-4127-9388-bc66a2944b4d", name="Way 3"}
breaker3 = {mrid="449b9433-af9b-4914-aa83-f119c11a962d", name="Breaker 3"}
way4 = {mrid="6e595d68-67b4-434c-8c26-736104cc14fe", name="Way 4"}
ion-lb= {mrid="2a09c597-d666-4354-a31a-dfe6da7727a9", name="Load Bank Meter"}
load-bank = {mrid="4cadfaed-4176-453d-9625-e9ae8ad70529", name="Load Bank"}
turbine-array = {mrid="8e202725-5a8d-45c2-b575-8161927c6770", name="Array"}
turbine1 = {mrid="d0e662ca-26a3-4c5d-a60f-0420978e1486", name="Turbine 1"}
turbine2 = {mrid="e4105c59-2b82-473c-89b4-74352a444c13", name="Turbine 2"}
satec_aux_saft = {mrid="2e8fbf26-a9ef-4fdd-8c5c-3f0d55b10000", name="SATEC AUX Saft"}
ion-shop = {mrid="0648ef71-cb63-4347-921a-9dbf178da687", name = "Shop Meter"}
sel751 = {mrid="081a9cd4-b7d2-4a7c-b089-42d0053f8e6a", name="Solar"}
parker-invert = {mrid="540b292a-e600-4ae4-b077-40b892ae6970", name="Solar Parker"}
weather-station = {mrid="9ad28dca-5bfb-49d6-9651-e59630129068", name="Weather Station"}
sat-gypsum = {mrid="f1ec4b3e-f43e-4d81-ae1c-30eb08b0d7c7", name="Gypsum Meter"}
eaton_m410 = {mrid="62f9785d-c5cd-4e3f-b41f-caac2e87cc92", name="Eaton M410"}

#"62d73f75-5c66-420d-81af-4267585c3e1e" = {name = "Breaker (B)", openfmb_type="breaker"}
#"28c0c3be-8f2e-4bea-bd21-2a9b62f7fbd4" = {name="Voltage Regulator (VT) -PhsA", openfmb_type="voltage_regulator"}
#"06858a8c-dc3a-414d-9b74-31a0a9715f6e" = {name="Voltage Regulator (VT) -PhsB", openfmb_type="voltage_regulator"}
#"86cd2185-0e3a-4e8e-8118-edefae74c84f" = {name="Voltage Regulator (VT) -PhsC",openfmb_type="voltage_regulator"}
#"ad334610-5655-482b-8cd3-f1a5cb54aa48" = {name="Cap Bank (C)", openfmb_type="shunt"}
#"6fb24895-b365-45bb-954a-055449bd9d56" = {name="Recloser (R1)", openfmb_type="recloser"}
#"4574d270-e9a3-42ab-a3cf-1ae06d063b83" =  {name="Recloser (R2)",openfmb_type="recloser"}
#"2a8194c5-4b81-4cc1-a121-77fe51b2b163" =  {name="Recloser (R4)",openfmb_type="recloser"}
#"ad532730-dfc4-4274-a7df-0b81bd97fb1c" =  {name="Recloser (R5)",openfmb_type="recloser"}
#"c8db06d5-94e5-4b88-a430-a0db4a2fee6e" =  {name="Pump Load",openfmb_type="load"}
#"925f712b-9151-4293-8569-6d7756671791" =  {name = "Air Switch (A2)",openfmb_tyhpe = "switch"}
#"b1723127-44cb-4df5-87d7-b794519a7943" =  {name = "Air Switch (A1)",openfmb_tyhpe = "switch"}
#"a557f914-1770-402f-b418-552acde5277d" =  {name = "Battery Invert (B|1)/ESS",openfmb_type = "ess"}
#"1509f3de-2ab6-403a-ac30-901463df8308" =  {name = "Solar Inverter (S|1)",openfmb_type = "solar"}

# min_soc =
# max_soc =
