[coordinator]
environment = "dev" # dev or prod
app_name = "openfmb-hmi" # name of the application
log-level = "Debug" # Off, Error, Info, Debug, Trace

[openfmb_nats_subscriber]
prod_uri = "10.10.200.111:32224"
dev_uri = "192.168.4.146:4222"
send_status_update = true
server_id = "741df6b5-5bdd-4ea6-a6aa-541fba744721"
# authentication_type = "creds"
# creds = "meter.creds"

[hmi]
server_host = "192.168.4.146"
server_port = 32771 # available ports are: 80 8080 443 32771 42771
ssl = true
ssl_cert = "certs/server/server-cert.pem"
ssl_key = "certs/server/server-key.pem"
http_scheme = "https"
ws_scheme = "ws"