[coordinator]
environment = "dev" # dev or prod
app_name = "openfmb-hmi" # name of the application
log-level = "Debug" # Off, Error, Info, Debug, Trace

[openfmb_nats_subscriber]
prod_uri = "10.10.200.111:32224"
dev_uri = "10.0.0.13:4222"
send_status_update = true
server_id = "741df6b5-5bdd-4ea6-a6aa-541fba744721"
# authentication_type = "creds"
# creds = "meter.creds"

[hmi]
server_host = "localhost"
server_port = 32771 # available ports are: 80 8080 443 32771 42771
ssl = true
ssl_cert = "certs/server/server-cert.pem"
ssl_key = "certs/server/server-key.pem"
http_scheme = "https"
ws_scheme = "ws"

[auth]
audience = "openfmb-hmi"
authorize_path = "authorize"
token_path = "oauth/token"
client_id = "Aex63pqZXhdvOuHbS1x3nwHk1TKc7i3L"
domain = "https://oes-dev.us.auth0.com"
scope = "openid profile email offline_access"
authority = "https://oes-dev.us.auth0.com/"
authorization_jwks_uri = "https://oes-dev.us.auth0.com/.well-known/jwks.json"
auth_logout = "https://oes-dev.us.auth0.com/v2/logout?client_id=Aex63pqZXhdvOuHbS1x3nwHk1TKc7i3L"