[coordinator]
environment = "dev" # dev or prod
app_name = "openfmb-hmi" # name of the application
log-level = "Debug" # Off, Error, Info, Debug, Trace

[openfmb_nats_subscriber]
prod_uri = "10.10.200.111:32224"
dev_uri = "10.0.0.13:4222"
send_status_update = true
server_id = "741df6b5-5bdd-4ea6-a6aa-541fba744721"
# authentication_type = "creds"
# creds = "meter.creds"

[hmi]
server_host = "localhost"
server_port = 32771 # available ports are: 80 8080 443 32771 42771
ssl = true
ssl_cert = "certs/server/server-cert.pem"
ssl_key = "certs/server/server-key.pem"
http_scheme = "https"
ws_scheme = "ws"

[auth]
audience = "gms"
authorize_path = "protocol/openid-connect/auth"
token_path = "protocol/openid-connect/token"
client_id = "gms"
domain = "https://localhost:8443/realms/oes"
scope = "openid profile email offline_access"
authority = "https://localhost:8443/realms/oes"
authorization_jwks_uri = "https://localhost:8443/realms/oes/protocol/openid-connect/certs"