name: CI to Docker Hub
on:
  push:
    # branches: [master]
env:
  GIT_TAGS: oesinc/openfmb.hmi:latest,oesinc/openfmb.hmi:${{ github.sha | cut -c1-7}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Clone submodule
        uses: actions/checkout@v2
        with:
          repository: openenergysolutions/openfmb-rs
          path: deps/openfmb-rs
          ssh-key: ${{ secrets.GH_OPENFMB_RS_KEY }}
          persist-credentials: true
      - name: Checkout submodule
        run: |
          git submodule init
          git submodule update

      - name: Test GitHASH
        shell: bash
        run: |
          echo env.GIT_SHORT_SHA

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: ${{ env.GIT_TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
