name: CI to Docker Hub
on:
  push:
    branches: [develop, OAuth]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: "oesinc/openfmb.hmi"
    steps:
      - name: Generate Docker Tags
        shell: bash
        run: |
          GIT_HASH=${{ github.sha }}
          GIT_HASH_SHORT=${GIT_HASH::8}
          
          if [[ "${{ github.event.repository.default_branch }}" == "${GITHUB_REF##*/}" ]]; then
            echo "DOCKER_TAGS=${{env.DOCKER_REPO}}:latest,${{env.DOCKER_REPO}}:${GIT_HASH_SHORT}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAGS=${{env.DOCKER_REPO}}:${GITHUB_REF##*/}-${GIT_HASH_SHORT}" >> $GITHUB_ENV
          fi

      - name: Verify Docker Tags
        shell: bash
        run: |
          if [[ -z "${{env.DOCKER_TAGS}}" ]]; then
            echo "DOCKER_TAGS is not assigned a value"
            exit 1
          fi

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Clone submodule
        uses: actions/checkout@v2
        with:
          repository: openenergysolutions/openfmb-rs
          path: deps/openfmb-rs
          ssh-key: ${{ secrets.GH_OPENFMB_RS_KEY }}
          persist-credentials: true

      - name: Checkout submodule
        run: |
          git submodule init
          git submodule update

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: ${{ env.DOCKER_TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
